(deftheme solarized-dark
  "Created 2011-07-02.")

(custom-theme-set-variables
 'solarized-dark
 )

(custom-theme-set-faces
 'solarized-dark
 '(cursor ((t (:foreground "#708183" :background "#042028" :inverse-video t))))
 '(escape-glyph-face ((t (:foreground "#c60007"))))
 '(fringe ((t (:foreground "#465a61" :background "#0a2832"))))
 '(linum ((t (:foreground "#465a61" :background "#0a2832"))))
 '(header-line ((t (:foreground "#708183" :background "#e9e2cb"))))
 '(highlight ((t (:background "#0a2832"))))
 '(hl-line ((t (:background "#0a2832"))))
 '(isearch ((t (:foreground "#a57705" :inverse-video t))))
 '(lazy-highlight ((t (:background "#e9e2cb" :foreground "#22373f"))))
 '(link ((t (:foreground "#5859b7" :underline t))))
 '(link-visited ((t (:foreground "#c61b6e" :underline t))))
 '(menu ((t (:foreground "#708183" :background "#0a2832"))))
 '(minibuffer-prompt ((t (:foreground "#2075c7"))))
 '(mode-line ((t (:foreground "#81908f" :background "#0a2832" :box (:line-width 1 :color "#81908f")))))
 '(mode-line-buffer-id ((t (:foreground "#81908f"))))
 '(mode-line-inactive ((t (:foreground "#708183" :background "#0a2832" :box (:line-width 1 :color "#0a2832")))))
 '(region ((t (:background "#0a2832"))))
 '(secondary-selection ((t (:background "#0a2832"))))
 '(trailing-whitespace ((t (:foreground "#c60007" :inverse-video t))))
 '(vertical-border ((t (:foreground "#708183"))))
 '(comint-highlight-prompt ((t (:foreground "#2075c7"))))
 '(compilation-info ((t (:foreground "#728a05" :weight bold))))
 '(compilation-warning ((t (:foreground "#bd3612" :weight bold))))
 '(custom-button ((t (:background "#0a2832" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((t (:inherit custom-button :foreground "#81908f"))))
 '(custom-button-pressed ((t (:inherit custom-button-mouse :box (:line-width 2 :style pressed-button)))))
 '(custom-comment-tag ((t (:background "#0a2832"))))
 '(custom-documentation ((t (:inherit default))))
 '(custom-group-tag ((t (:foreground "#bd3612" :weight bold))))
 '(custom-link ((t (:foreground "#5859b7"))))
 '(custom-state ((t (:foreground "#728a05"))))
 '(custom-variable-tag ((t (:foreground "#bd3612" :weight bold))))
 '(diff-added ((t (:foreground "#728a05" :inverse-video t))))
 '(diff-changed ((t (:foreground "#a57705" :inverse-video t))))
 '(diff-removed ((t (:foreground "#c60007" :inverse-video t))))
 '(diff-header ((t (:background "#465a61"))))
 '(diff-file-header ((t (:background "#81908f" :foreground "#465a61" :weight bold))))
 '(diff-refine-change ((t (:background "#81908f"))))
 '(ido-only-match ((t (:foreground "#728a05"))))
 '(ido-subdir ((t (:foreground "#2075c7"))))
 '(ido-first-match ((t (:foreground "#728a05" :weight bold))))
 '(emacs-wiki-bad-link-face ((t (:foreground "#c60007" :underline t))))
 '(emacs-wiki-link-face ((t (:foreground "#2075c7" :underline t))))
 '(emacs-wiki-verbatim-face ((t (:foreground "#22373f" :underline t))))
 '(font-lock-builtin-face ((t (:foreground "#728a05"))))
 '(font-lock-comment-face ((t (:foreground "#465a61" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#259185"))))
 '(font-lock-function-name-face ((t (:foreground "#2075c7"))))
 '(font-lock-keyword-face ((t (:foreground "#728a05"))))
 '(font-lock-string-face ((t (:foreground "#259185"))))
 '(font-lock-type-face ((t (:foreground "#a57705"))))
 '(font-lock-variable-name-face ((t (:foreground "#2075c7"))))
 '(font-lock-warning-face ((t (:foreground "#c60007" :weight bold))))
 '(font-lock-doc-face ((t (:foreground "#259185" :slant italic))))
 '(font-lock-color-constant-face ((t (:foreground "#728a05"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#465a61" :weight bold))))
 '(font-lock-doc-string-face ((t (:foreground "#728a05"))))
 '(font-lock-preprocessor-face ((t (:foreground "#bd3612"))))
 '(font-lock-reference-face ((t (:foreground "#259185"))))
 '(font-lock-negation-char-face ((t (:foreground "#c60007"))))
 '(font-lock-other-type-face ((t (:foreground "#2075c7" :slant italic))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#bd3612"))))
 '(font-lock-special-keyword-face ((t (:foreground "#c61b6e"))))
 '(font-lock-exit-face ((t (:foreground "#c60007"))))
 '(font-lock-other-emphasized-face ((t (:foreground "#5859b7" :weight bold :slant italic))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#a57705"))))
 '(info-xref ((t (:foreground "#2075c7" :underline t))))
 '(info-xref-visited ((t (:inherit info-xref :foreground "#c61b6e"))))
 '(org-hide ((t (:foreground "#042028"))))
 '(org-todo ((t (:foreground "#042028" :background "#c60007" :weight bold))))
 '(org-done ((t (:foreground "#728a05" :weight bold))))
 '(org-todo-kwd-face ((t (:foreground "#c60007" :background "#042028"))))
 '(org-done-kwd-face ((t (:foreground "#728a05" :background "#042028"))))
 '(org-project-kwd-face ((t (:foreground "#5859b7" :background "#042028"))))
 '(org-waiting-kwd-face ((t (:foreground "#bd3612" :background "#042028"))))
 '(org-someday-kwd-face ((t (:foreground "#2075c7" :background "#042028"))))
 '(org-started-kwd-face ((t (:foreground "#a57705" :background "#042028"))))
 '(org-cancelled-kwd-face ((t (:foreground "#728a05" :background "#042028"))))
 '(org-delegated-kwd-face ((t (:foreground "#259185" :background "#042028"))))
 '(show-paren-match ((t (:background "#259185" :foreground "#fcf4dc"))))
 '(show-paren-mismatch ((t (:background "#c60007" :foreground "#fcf4dc"))))
 '(widget-field ((t (:box (:line-width 1 :color "#22373f") :inherit default))))
 '(widget-single-line-field ((t (:inherit widget-field))))
 '(gnus-cite-1 ((t (:foreground "#c61b6e"))))
 '(gnus-cite-2 ((t (:foreground "#e9e2cb"))))
 '(gnus-cite-3 ((t (:foreground "#fcf4dc"))))
 '(gnus-cite-4 ((t (:foreground "#81908f"))))
 '(gnus-cite-5 ((t (:foreground "#c61b6e"))))
 '(gnus-cite-6 ((t (:foreground "#e9e2cb"))))
 '(gnus-cite-7 ((t (:foreground "#fcf4dc"))))
 '(gnus-cite-8 ((t (:foreground "#81908f"))))
 '(gnus-cite-9 ((t (:foreground "#e9e2cb"))))
 '(gnus-cite-10 ((t (:foreground "#fcf4dc"))))
 '(gnus-cite-11 ((t (:foreground "#2075c7"))))
 '(gnus-group-mail-1 ((t (:foreground "#fcf4dc" :weight bold))))
 '(gnus-group-mail-1-empty ((t (:foreground "#fcf4dc"))))
 '(gnus-group-mail-2 ((t (:foreground "#e9e2cb" :weight bold))))
 '(gnus-group-mail-2-empty ((t (:foreground "#e9e2cb"))))
 '(gnus-group-mail-3 ((t (:foreground "#c61b6e" :weight bold))))
 '(gnus-group-mail-3-empty ((t (:foreground "#c61b6e"))))
 '(gnus-group-mail-low ((t (:foreground "#22373f" :weight bold))))
 '(gnus-group-mail-low-empty ((t (:foreground "#22373f"))))
 '(gnus-group-news-1 ((t (:foreground "#81908f" :weight bold))))
 '(gnus-group-news-1-empty ((t (:foreground "#81908f"))))
 '(gnus-group-news-2 ((t (:foreground "#2075c7" :weight bold))))
 '(gnus-group-news-2-empty ((t (:foreground "#2075c7"))))
 '(gnus-group-news-low ((t (:foreground "#5859b7" :weight bold))))
 '(gnus-group-news-low-empty ((t (:foreground "#5859b7"))))
 '(gnus-header-content ((t (:foreground "#259185" :slant italic))))
 '(gnus-header-from ((t (:foreground "#e9e2cb"))))
 '(gnus-header-name ((t (:foreground "#2075c7"))))
 '(gnus-header-newsgroups ((t (:foreground "#728a05" :slant italic))))
 '(gnus-header-subject ((t (:foreground "#81908f"))))
 '(gnus-server-agent ((t (:foreground "#fcf4dc" :weight bold))))
 '(gnus-server-closed ((t (:foreground "#81908f" :slant italic))))
 '(gnus-server-denied ((t (:foreground "#e9e2cb" :weight bold))))
 '(gnus-server-offline ((t (:foreground "#728a05" :weight bold))))
 '(gnus-server-opened ((t (:foreground "#259185" :weight bold))))
 '(gnus-splash ((t (:foreground "#e9e2cb"))))
 '(gnus-summary-high-ancient ((t (:foreground "#c61b6e" :weight bold))))
 '(gnus-summary-high-read ((t (:foreground "#81908f" :weight bold))))
 '(gnus-summary-high-ticked ((t (:foreground "#fcf4dc" :weight bold))))
 '(gnus-summary-high-undownloaded ((t (:foreground "#e9e2cb" :weight bold))))
 '(gnus-summary-low-ancient ((t (:foreground "#c61b6e" :slant italic))))
 '(gnus-summary-low-read ((t (:foreground "#81908f" :slant italic))))
 '(gnus-summary-low-ticked ((t (:foreground "#fcf4dc" :slant italic))))
 '(gnus-summary-low-undownloaded ((t (:foreground "#e9e2cb" :slant italic))))
 '(gnus-summary-normal-ancient ((t (:foreground "#c61b6e"))))
 '(gnus-summary-normal-read ((t (:foreground "#81908f"))))
 '(gnus-summary-normal-ticked ((t (:foreground "#fcf4dc"))))
 '(gnus-summary-normal-undownloaded ((t (:foreground "#e9e2cb"))))
 '(flymake-errline ((t (:background "#bd3612"))))
 '(flymake-warnline ((t (:background "#5859b7"))))
 '(whitespace-empty ((t (:foreground "#c60007"))))
 '(whitespace-hspace ((t (:foreground "#bd3612"))))
 '(whitespace-indentation ((t (:foreground "#0a2832"))))
 '(whitespace-space ((t (:foreground "#0a2832"))))
 '(whitespace-space-after-tab ((t (:foreground "#259185"))))
 '(whitespace-space-before-tab ((t (:foreground "#c60007" :weight bold))))
 '(whitespace-tab ((t (:foreground "#0a2832"))))
 '(whitespace-trailing ((t (:background "#0a2832" :foreground "#c60007" :weight bold))))
 '(whitespace-highlight-face ((t (:background "#2075c7" :foreground "#c60007"))))
 '(message-mml ((t (:foreground "#2075c7"))))
 '(message-cited-text ((t (:foreground "#e9e2cb"))))
 '(message-separator ((t (:foreground "#fcf4dc"))))
 '(message-header-xheader ((t (:foreground "#5859b7"))))
 '(message-header-name ((t (:foreground "#259185"))))
 '(message-header-other ((t (:foreground "#c60007"))))
 '(message-header-newsgroups ((t (:foreground "#a57705" :weight bold :slant italic))))
 '(message-header-subject ((t (:foreground "#22373f"))))
 '(message-header-cc ((t (:foreground "#728a05" :weight bold))))
 '(message-header-to ((t (:foreground "#81908f" :weight bold))))
 '(default ((t (:background "#042028" :foreground "#708183")))))

(provide-theme 'solarized-dark)
